config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users

  post "/emails/create", as: :create_email

  authenticated :user do
    root 'welcome#index'
  end

  unauthenticated :user do
    devise_scope :user do
      root "welcome#unregistered", as: :unregistered_root
    end
  end  
end

app/models/my_email.rb
class MyEmail < ActiveRecord::Base
	validates_presence_of :email, message: "No olvide escribir un correo electrónico por favor"
	validates_uniqueness_of :email, message: "Este correo ya fue registrado"
	validates_format_of :email, with: Devise::email_regexp
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :name,:pricing #,:user
  validates :pricing, numericality: { greater_than: 0}

  has_attached_file :avatar, styles: { medium: "300x300", thumb:"100x100 "}, default_url: "missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def create
  	@email = MyEmail.new(email: params[:email])
  		if @email.save
  			render json: @email
  		else
  			render json: @email.errors, status: :unprocessable_entity
  		end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!,except: [:index,:show,:products]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    #@product = current_user.product.new(product_params)
    @product = Product.new(product_params)
    @product.user = current_user
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1º
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :pricing, :description,:avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def unregistered
  	render layout: "landing"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div style="<%= "display:none;" if alert.nil? && notice.nil? %>">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>		
	</div>

<%= yield %>

</body>
</html>

app/views/layouts/landing.haml
!!!5
%html
	%head
		%title Pago Online FI
		= stylesheet_link_tag 'landing', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
	%div{style:" #{"display:none;" if alert.nil? && notice.nil?} "}
		%p.notice= notice
		%p.alert= alert
	=yield

app/views/products/_form.html.haml
= form_for @product,builder: BootstrapFormBuilder do |f|
  = f.errors
  = f.text_field :name
  = f.text_field :pricing
  = f.file_field :avatar
  = f.text_area :description
  = f.submit "Enviar"

app/views/products/edit.html.haml
.col-md-10.col-xs-12.col-sm-11.no-float.center-block
	.card.large-padding
		%h2 Editar producto

		= render 'form'

app/views/products/index.html.haml
%h3 Listing products

%table
  %thead
    %tr
      %th Name
      %th Pricing
      %th Description
      %th User
      %th
      %th
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td= product.name
        %td= product.pricing
        %td= product.description
        %td= product.user
        %td= link_to 'Show', product
        %td= link_to 'Edit', edit_product_path(product)
        %td= link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Product', new_product_path

app/views/products/new.html.haml
.col-md-10.col-xs-12.col-sm-11.no-float.center-block
	.card.large-padding
		%h2 Agregar producto

		= render 'form'

app/views/products/show.html.haml
.col-lg-7.col-md-8.col-xs-12.col-sm-10.no-float.center-block
	%article.card.big-padding
		%header
			%h1.grey-text.bold= @product.name
		%section
			.col-xs-6.col-md-5.no-padding.inline-block
				=image_tag @product.avatar.url
			.col-md-1.inline-block.hidden-xs
			.col-xs-5.col-md-6.inline-block.text-left
				%h3.blue-text.bold.normal email.com
				%h3.teal-text.bold.normal
					Precio:
					%span.teal-text= "$#{@product.pricing}"
				%h3.teal-text.blod.normal
					Clave:
					%span.teal-text claveProduct
		%section
			%h3.green-text.bold.normal Descripción
			%p= @product.description

app/views/welcome/index.haml
%h1 Bienvenido


%p 
	=link_to "Cerrar sesión", destroy_user_session_path, method: :delete

app/views/welcome/unregistered.haml
%header.red.big-padding
	.col-md-10.no-float.center-block
		.col-md-6.no-padding.inline-block
			=image_tag "Logo.png",width:"100"
			%p.cream-text
				Factura Inteligente
			%h1.cream-text.ultra-big.kostic
				%strong
					Pago Online
				%p de productos digitales.
		.col-md-5.inline-block
			=image_tag "mobile_payment.png"

.cream.black-text.big-padding.kostic
	.col-md-10.no-float.center-block
		.absolute{style:"bottom:-4.5em; width: 100%; left:0px;"}
			.text-center.big
				.col-md-3.inline-block
					.white.black-text.circle
						%strong 1
				.col-md-3.inline-block
					.white.black-text.circle
						%strong 2
				.col-md-3.inline-block
					.white.black-text.circle
						%strong 3

		%h2.bigger.text-center
			%strong
				En 3 sencillos pasos
		%div.text-center
			.col-md-3.inline-block.text-left
				=image_tag "upload-icon.png", class:"col-md-10 inline-block"
				.top-space
					%span.bigger.black-text
						Paso uno
					%p.strong-blue-text.text-justify.medium
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus animi atque officiis laborum sapiente ut, quibusdam, facilis ex voluptas modi. Debitis distinctio nulla vel ipsum? Repellendus pariatur non incidunt vero.
			.col-md-3.inline-block.text-left
				=image_tag "upload-icon.png", class:"col-md-10 inline-block"
				.top-space
					%span.bigger.black-text
						Paso dos
					%p.strong-blue-text.text-justify.medium
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus animi atque officiis laborum sapiente ut, quibusdam, facilis ex voluptas modi. Debitis distinctio nulla vel ipsum? Repellendus pariatur non incidunt vero.
			.col-md-3.inline-block.text-left
				=image_tag "upload-icon.png", class:"col-md-10 inline-block"
				.top-space
					%span.bigger.black-text
						Paso tres
					%p.strong-blue-text.text-justify.medium
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus animi atque officiis laborum sapiente ut, quibusdam, facilis ex voluptas modi. Debitis distinctio nulla vel ipsum? Repellendus pariatur non incidunt vero.

.dark-blue.cream-text.big-padding.kostic{style:"margin-top: 5em;"}
	.col-md-8.no-float.text-center.center-block
		=image_tag "media-icons.png"
		%p.medium.col-md-11.center-block.no-float
			Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos, numquam ducimus! Culpa quas deleniti unde, voluptates id officia, sunt, autem quae aspernatur cum cupiditate a ea maiores nostrum quis corporis.

.top-space.big-padding.bottom-space
	.col-md-11.col.xs-12.center-block.no-float
		=form_tag(create_email_path,method: :post,remote:true,id:"emails-form") do
			=email_field_tag "email", nil, class: "col-xs-12 inline-block text-center landing-form", placeholder: "Escriba su correo"
		#email-info.red.cream-text.large-padding